[package]
name = "advent_of_code_2018"
version = "0.1.0"
authors = ["Daniel Buse <daniel.buse@gmx.de>"]

[dependencies]
itertools = "0.7"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"